### PR TITLE
Implement computation graph API with type safety, error message plumbing, and dimensionality checks

### PR DESCRIPTION
**Pull request by rodolphito**
Hey Braden!

I'm Eben's friend, I originally found and linked your project to them after running into it the other day. I work in rust, primarily with Bevy. I greatly appreciate the enthusiasm and responsiveness you've shown :)

Eben and I discussed the requirements of the computation graph API and autodifferentiation, here I have written a first pass. Feel free to iterate on it with them, and ask me about anything more involved with Rust's type system, lifetimes, or macros.

I also have some advice for your codebase:

1. Enable format-on-save on your IDE, and run `rustfmt` on your repository. If you're on VS Code, place this in your settings.json:
```
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "editor.formatOnSave": true,
```
2. Configure clippy on your IDE, or run `cargo check clippy`. it yells about things that make sense most of the time. It is currently erroring on `self.columns != self.columns` in `data/matrix.rs::349`, and giving many more warnings
3. Use sub-crates for better separation of concerns and faster compile times. You can do this by making a `crates` folder at the root of the repository, making a folder in it for every subcrate, and having a Cargo.toml for each, with a `src` dir in each too. You can then make the main crate pull in all the sub crates and re-export an API. Check out how the Bevy game engine or wgpu project has their project structured for inspiration. Don't publish the subcrates though.
4. Use less specific versions in your Cargo.toml. Most of the time its better to only specify the first two digits, you don't need a specific patch version because of semver guarantees.

### CODE REVIEW

**Comment by Ebanflo42** [comment]
Leave it to ro to design something this powerful overnight 😆 

This branch outlines the solutions to a lot of the high-level problems I was talking about. Breaking it down by module (these should definitely be more commented in the near future):

`operation` defines nodes of the compute graph. Currently this is a placeholder and I can rework them to actual XLA operations and then start the compilation aspect.

`context` defines the graph as a slotmap holding operation nodes, basically the operations need to reference their arguments and consistently need to know where they are in the graph. What's really great about the design here, as seen in `mod.rs`, someone can say `ctx.my_math_op(identifier)` (for example `my_math_op` will eventually be matrix multiplication or convolution or something) and this augments the compute graph automatically, without the user having to mess with the graph explicitly. This is similar to the TensorFlow 1 API (but nicer) if you have ever seen that.

`callsite` is some magic which allows errors to be called directly where `ctx.my_math_op` is called, this will honestly give us superior debugging to TensorFlow, and at least on the same level as JAX.

Finally `dimension` can shape check tensor placeholders, and automatically names things as scalars, vectors, matrices, tensors, etc.

For the naming conventions, I think it basically makes sense, but they are all very overloaded terms used in other crates I'm sure. One thing I would think of is renaming `Operation` to `UndaOp`, `Node` to `UndaNode`, `Context` to `UndaContext`, etc

**Comment by BradenEverson** [comment]
Hey Ro, this is genuinely amazing stuff! I really appreciate the progress :) I just woke up but I'll get this merged in soon and look towards doing some of the renames Eben mentioned and going from there. Thank you as well for the advice on the crate structure itself! I'm definitely very new to rust, and in fact this project was sort of my attempt at actually learning deeper about the structure of rust and where it's strengths come from. 

This beginning code for computes, operations and nodes seems very promising

**Comment by Ebanflo42** [comment]
My next plan would be to augment ro's basis for the compute graphs using actual XLA ops. Since there is already the xla_rs branch, should we also pull the changes into that one so I can branch off of it?

**Comment by rodolphito** [comment]
I've implemented really basic autodiff to show how to transform the compute graph. Just product rule and addition and parameter/constant logic. In-place mutation with callsite propagation will make this very easy to debug. Theres one more thing i want to add to make it easier for yall, i'm gonna add a mode that prints the full AST in-between every single autodiff substitution step.

**Comment by rodolphito** [comment]
Also, including the project name in types is not common in Rust due to namespacing. Most of the time its not necessary, for example check the Bevy repo, you'll be hard-pressed to find a BevyXX type. On the other hand, wgpu does have a `WgpuContext` type, so `UndaContext` may be justified :)

**Comment by Ebanflo42** [comment]
This is looking pretty nice. So the `Diff` node of the compute graph basically marks an output which we want to differentiate? This augmenting the compute graph so that it essentially describes both the forward and backward pass right?

**Comment by rodolphito** [comment]
Yep, and all the autodiff happens in place to avoid needing to hunt down references to nodes in the slotmap. So anything referencing the Diff node continues to reference the slot where the Diff node was, except now it has an expanded computation.

The basic rule is: Diff nodes can get replaced by other nodes, but other nodes may NEVER be replaced during autodiff, because other non-differentiating computations may be referencing them too. So whenever expanding a Diff node, create a couple new Diff nodes for the arguments, wrapping the original arguments, and reference those new Diff nodes in the lifted op node.

**Comment by BradenEverson** [comment]
> My next plan would be to augment ro's basis for the compute graphs using actual XLA ops. Since there is already the xla_rs branch, should we also pull the changes into that one so I can branch off of it?

If you want to work off of `xla_rs` that works with me! Or if you want to just make a new branch feel free to, not a bunch has been done in that branch so if you do just make a new one I can delete `xla_rs` :)

**Comment by BradenEverson** [comment]
So my main question now is how we want to implement this over in the context of the existing network code. I think it would be smart to rename the Network struct to something like Sequential as Tensorflow has, as this will define the behavior for a network that is strictly linear in its operations. As Dense layers are just 'fully connected' layers in the graph context, would we want to keep the Trait for layers and refactor the internal logic for Dense to use these graph structs, or were you all thinking something else? 

As of right now, I want to work on getting optimizers set to be an enum that can be referenced during backprop, and then based on what you guys think, I can work on porting the existing Dense logic to use the graph backend :D

**Pull request merged**
